# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOuNPuupQWtb9EEX7b0OKtL3qQJnQVMD
"""

#@title Inserisci i Valori per il Confronto
good = 990 #@param {type:"integer"}
default = 10 #@param {type:"integer"}
model_pd = 0.02 #@param {type:"number"}

# Calcola N (numero totale di controparti)
N_total = good + default

# Calcola TD (Tasso di Default osservato)
td_observed = default / N_total if N_total > 0 else 0

print(f"Numero di casi 'Good': {good}")
print(f"Numero di 'Default' osservati: {default}")
print(f"PD del modello: {model_pd:.4f}")
print(f"Numero totale di controparti (N): {N_total}")
print(f"Tasso di Default osservato (TD): {td_observed:.4f}")

# Esegui la comparazione con i valori inseriti
if N_total > 0:
    p_jeffreys, p_binomial = compare_tests(N_total, model_pd, defaults=default)
    print(f"\nRisultati del Confronto:")
    print(f"  Jeffrey's Test P-Value: {p_jeffreys:.4f}")
    print(f"  Binomial Test P-Value: {p_binomial:.4f}")

    # Generate a range for plotting, centered around N_total
    plot_N_start = max(default, 10)
    # Extend the range to about 50% more than N_total, ensuring a decent plot
    plot_N_end = N_total + int(N_total * 0.5)
    plot_N_range = np.arange(plot_N_start, plot_N_end + 1, 10)

    print(f"\nGenerazione grafico per {default} default e PD del modello {model_pd:.4f} su un range di N.")
    plot_comparison_multiple_defaults(plot_N_range, model_pd, default)

else:
    print("\nImpossibile eseguire il confronto: il numero totale di controparti è zero.")
